name: Bug Report
title: 'Bug: '
description: Report a bug to help us improve BaseCompose
labels: ['bug', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please provide as much detail as possible.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what went wrong
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Expected behavior
    validations:
      required: true
  
  - type: input
    id: node_version
    attributes:
      label: Node Version
      description: What version of Node.js are you using?
      placeholder: e.g., 18.0.0
    validations:
      required: true
  
  - type: input
    id: pnpm_version
    attributes:
      label: pnpm Version
      description: What version of pnpm are you using?
      placeholder: e.g., 8.0.0
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: e.g., macOS, Windows, Linux
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else that might help?
      placeholder: Screenshots, error logs, etc.
