import * as fs from "fs";
import * as path from "path";
import type { GenerationState, CollectedEnv } from "../types";

/**
 * Load environment variables from addon env.ts files
 */
export function loadAddonEnv(
  addon: string,
  templatesRoot: string
): CollectedEnv {
  let envPath: string;

  if (addon === "mongodb") {
    envPath = path.join(templatesRoot, "databases/mongodb/env.ts");
  } else if (addon === "authjs") {
    envPath = path.join(templatesRoot, "auth/authjs/env.ts");
  } else if (addon === "demo") {
    // Demo doesn't have env vars
    return {};
  } else {
    throw new Error(`Unknown addon: ${addon}`);
  }

  if (!fs.existsSync(envPath)) {
    console.warn(`Addon env not found: ${envPath}`);
    return {};
  }

  // Read the env.ts file and parse it
  const content = fs.readFileSync(envPath, "utf-8");

  // Simple regex-based extraction of env object
  // Pattern: export const env = { KEY: "value", ... }
  const envMatch = content.match(/export const env = ({[\s\S]*?});/);
  if (!envMatch) {
    console.warn(`Could not parse env from ${envPath}`);
    return {};
  }

  // Parse the object literal
  try {
    // Replace problematic characters and evaluate
    let objStr = envMatch[1];
    // Extract key-value pairs safely
    const pairs: CollectedEnv = {};
    const regex = /(\w+):\s*"([^"]*)"/g;
    let match;
    while ((match = regex.exec(objStr)) !== null) {
      pairs[match[1]] = match[2];
    }
    return pairs;
  } catch (err) {
    console.warn(`Error parsing env from ${envPath}:`, err);
    return {};
  }
}

/**
 * Collect all environment variables from selected addons
 */
export function collectAddonEnv(state: GenerationState) {
  const templatesRoot = path.resolve(process.cwd(), "templates");

  for (const addon of state.context.addons) {
    const addonEnv = loadAddonEnv(addon, templatesRoot);
    state.env = { ...state.env, ...addonEnv };
  }

  console.log(`✓ Collected env vars:`, Object.keys(state.env));
}

/**
 * Generate .env.example file
 */
export function generateEnvExample(state: GenerationState): string {
  const lines: string[] = ["# Environment Variables", "# Generated by Layered"];

  if (Object.keys(state.env).length === 0) {
    return lines.join("\n");
  }

  lines.push("");
  for (const [key, value] of Object.entries(state.env)) {
    if (value) {
      lines.push(`${key}=${value}`);
    } else {
      lines.push(`${key}=`);
    }
  }

  return lines.join("\n");
}

/**
 * Write .env.example to output directory
 */
export function writeEnvExample(state: GenerationState) {
  const envExample = generateEnvExample(state);
  const envPath = path.join(state.context.outDir, ".env.example");

  fs.writeFileSync(envPath, envExample, "utf-8");
  console.log(`✓ .env.example written`);
}
